version: 2
jobs:
  runtest:
    macos:
      xcode: "10.0.0"
    working_directory: ~/purchases-ios
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Run tests
          command: fastlane scan
workflows:
  version: 2
  build-test:
    jobs:
      - runtest